# The URL the site will be built for
base_url = "https://perfectday20.me"
title = "PerfectDay20's Blog"
description = "no desc"

theme = "hook"
# The default language; used in feeds and search index
# Note: the search index doesn't support Chinese/Japanese/Korean Languages
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to generate a feed file for the site
generate_feeds = true

# When set to "true", the generated HTML files are minified.
minify_html = true

# The taxonomies to be rendered for the site and their configuration.
taxonomies = [
  {name = "categories"}, # Basic definition: no feed or pagination
  {name = "tags"}, # Basic definition: no feed or pagination
]

[markdown]
highlight_code = true
highlight_theme = "solarized-light"

[extra]
# Put all your custom variables here

links = [
    { title = "GitHub", href = "https://github.com/PerfectDay20" },
    { title = "RSS", href = "atom.xml" },
]
